import { MongoClient } from "mongodb";

const uri =
  "mongodb+srv://Amal:amal@mdplanner.joa9bqf.mongodb.net/?retryWrites=true&w=majority&appName=mdplanner";
const client = new MongoClient(uri);

const mainDishes = [
  // Main dishes
  {
    name: "idli",
    meal: "breakfast",
    category: "main dish",
    servings: [
      {
        type: "idli(regular)",
        quantity: 1,
        weight_grams: 50.0,
        calories: 73,
        protein: 2.2,
        fat: 0.3,
        carbs: 15.2,
        fiber: 1.3,
      },
      {
        type: "idli(small)",
        quantity: 1,
        weight_grams: 25.0,
        calories: 36,
        protein: 1.1,
        fat: 0.2,
        carbs: 7.6,
        fiber: 0.7,
      },
      {
        type: "piece",
        quantity: 1,
        weight_grams: 50.0,
        calories: 73,
        protein: 2.2,
        fat: 0.3,
        carbs: 15.2,
        fiber: 1.3,
      },
    ],
  },
  {
    name: "dosa",
    meal: ["breakfast", "dinner"],
    category: "main dish",
    servings: [
      {
        type: "medium",
        quantity: 1,
        weight_grams: 80.0,
        calories: 147,
        protein: 3.6,
        fat: 4.7,
        carbs: 22.6,
        fiber: 1.3,
      },
      {
        type: "small",
        quantity: 1,
        weight_grams: 60.0,
        calories: 110,
        protein: 2.7,
        fat: 3.5,
        carbs: 17.0,
        fiber: 0.9,
      },
      {
        type: "piece",
        quantity: 1,
        weight_grams: 80.0,
        calories: 147,
        protein: 3.6,
        fat: 4.7,
        carbs: 22.6,
        fiber: 1.3,
      },
      {
        type: "large",
        quantity: 1,
        weight_grams: 120.0,
        calories: 221,
        protein: 5.4,
        fat: 7.1,
        carbs: 33.9,
        fiber: 1.9,
      },
    ],
  },
  {
    name: "appam",
    meal: ["breakfast", "dinner"],
    category: "main dish",
    servings: [
      {
        type: "regular",
        quantity: 1,
        weight_grams: 60.0,
        calories: 116,
        protein: 2.4,
        fat: 1.9,
        carbs: 22.5,
        fiber: 0.9,
      },
      {
        type: "piece",
        quantity: 1,
        weight_grams: 60.0,
        calories: 116,
        protein: 2.4,
        fat: 1.9,
        carbs: 22.5,
        fiber: 0.9,
      },
    ],
  },
  {
    name: "idiyappam",
    meal: ["breakfast", "dinner"],
    category: "main dish",
    servings: [
      {
        type: "regular",
        quantity: 1,
        weight_grams: 50.0,
        calories: 77,
        protein: 1.2,
        fat: 0.8,
        carbs: 15.7,
        fiber: 0.5,
      },
      {
        type: "piece",
        quantity: 1,
        weight_grams: 50.0,
        calories: 77,
        protein: 1.2,
        fat: 0.8,
        carbs: 15.7,
        fiber: 0.5,
      },
    ],
  },
  {
    name: "puttu",
    meal: "breakfast",
    category: "main dish",
    servings: [
      {
        type: "portion(1/3 of kutti)",
        quantity: 1,
        weight_grams: 100.0,
        calories: 194,
        protein: 2.9,
        fat: 4.9,
        carbs: 33.9,
        fiber: 2.4,
      },
      {
        type: "cup/chiratta",
        quantity: 1,
        weight_grams: 150.0,
        calories: 291,
        protein: 4.3,
        fat: 7.3,
        carbs: 50.8,
        fiber: 3.6,
      },
      {
        type: "kutti/kulai/cylinder",
        quantity: 1,
        weight_grams: 300.0,
        calories: 583,
        protein: 8.6,
        fat: 14.6,
        carbs: 101.6,
        fiber: 7.1,
      },
    ],
  },
  {
    name: "kuthari choru",
    meal: ["lunch", "dinner"],
    category: "main dish",
    servings: [
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 124.0,
        calories: 114,
        protein: 1.9,
        fat: 0.0,
        carbs: 26.7,
        fiber: 0.4,
      },
      {
        type: "cup",
        quantity: 1,
        weight_grams: 206.0,
        calories: 190,
        protein: 3.2,
        fat: 0.0,
        carbs: 44.4,
        fiber: 0.7,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 289.0,
        calories: 267,
        protein: 4.5,
        fat: 0.0,
        carbs: 62.3,
        fiber: 1.0,
      },
    ],
  },
  {
    name: "white rice",
    meal: ["lunch", "dinner"],
    category: "main dish",
    servings: [
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 124.0,
        calories: 120,
        protein: 2.6,
        fat: 0.4,
        carbs: 26.7,
        fiber: 0.5,
      },
      {
        type: "cup",
        quantity: 1,
        weight_grams: 206.0,
        calories: 200,
        protein: 4.4,
        fat: 0.6,
        carbs: 44.4,
        fiber: 0.8,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 289.0,
        calories: 281,
        protein: 6.1,
        fat: 0.8,
        carbs: 62.2,
        fiber: 1.1,
      },
    ],
  },
];

const curries = [
  // curries
  {
    name: "kadala curry",
    meal: ["breakfast", "dinner"],
    category: "curry",
    servings: [
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 150.0,
        calories: 168,
        protein: 6.2,
        fat: 5.7,
        carbs: 23.2,
        fiber: 10.5,
      },
      {
        type: "cup",
        quantity: 1,
        weight_grams: 250.0,
        calories: 279,
        protein: 10.4,
        fat: 9.5,
        carbs: 38.6,
        fiber: 17.5,
      },
      {
        type: "bowl",
        quantity: 1,
        weight_grams: 350.0,
        calories: 391,
        protein: 14.5,
        fat: 13.3,
        carbs: 54.1,
        fiber: 24.4,
      },
    ],
  },
  {
    name: "cherupayar curry",
    meal: "breakfast",
    category: "curry",
    servings: [
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 150.0,
        calories: 167,
        protein: 7.6,
        fat: 6.9,
        carbs: 19.1,
        fiber: 7.0,
      },
      {
        type: "cup",
        quantity: 1,
        weight_grams: 250.0,
        calories: 279,
        protein: 12.6,
        fat: 11.4,
        carbs: 31.8,
        fiber: 11.6,
      },
      {
        type: "bowl",
        quantity: 1,
        weight_grams: 350.0,
        calories: 390,
        protein: 17.7,
        fat: 16.0,
        carbs: 44.5,
        fiber: 16.3,
      },
    ],
  },
  {
    name: "sambar",
    meal: ["breakfast, lunch, dinner"],
    category: "curry",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 250.0,
        calories: 189,
        protein: 9.2,
        fat: 5.0,
        carbs: 27.0,
        fiber: 6.1,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 150.0,
        calories: 114,
        protein: 5.5,
        fat: 3.0,
        carbs: 16.2,
        fiber: 3.7,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 350.0,
        calories: 265,
        protein: 12.8,
        fat: 7.0,
        carbs: 37.8,
        fiber: 8.6,
      },
    ],
  },
  {
    name: "mutta curry",
    meal: ["breakfast", "dinner"],
    category: "curry",
    servings: [
      {
        type: "serve(1 egg + curry)",
        quantity: 1,
        weight_grams: 151.0,
        calories: 160,
        protein: 7.2,
        fat: 12.4,
        carbs: 4.7,
        fiber: 1.5,
      },
      {
        type: "cup",
        quantity: 1,
        weight_grams: 250.0,
        calories: 266,
        protein: 11.9,
        fat: 20.6,
        carbs: 7.8,
        fiber: 2.5,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 150.0,
        calories: 159,
        protein: 7.1,
        fat: 12.3,
        carbs: 4.7,
        fiber: 1.5,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 350.0,
        calories: 372,
        protein: 16.6,
        fat: 28.8,
        carbs: 10.9,
        fiber: 3.5,
      },
    ],
  },
  {
    name: "vegetable stew",
    meal: "breakfast",
    category: "curry",
    servings: [
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 150.0,
        calories: 112,
        protein: 2.0,
        fat: 8.2,
        carbs: 8.8,
        fiber: 2.4,
      },
      {
        type: "cup",
        quantity: 1,
        weight_grams: 250.0,
        calories: 186,
        protein: 3.3,
        fat: 13.6,
        carbs: 14.7,
        fiber: 3.9,
      },
      {
        type: "bowl",
        quantity: 1,
        weight_grams: 350.0,
        calories: 260,
        protein: 4.6,
        fat: 19.0,
        carbs: 20.6,
        fiber: 5.5,
      },
    ],
  },
  {
    name: "rasam",
    meal: ["lunch", "dinner"],
    category: "curry",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 250.0,
        calories: 60,
        protein: 2.5,
        fat: 1.3,
        carbs: 9.6,
        fiber: 1.7,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 150.0,
        calories: 36,
        protein: 1.5,
        fat: 0.8,
        carbs: 5.8,
        fiber: 1.0,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 350.0,
        calories: 84,
        protein: 3.5,
        fat: 1.9,
        carbs: 13.4,
        fiber: 2.4,
      },
    ],
  },
  {
    name: "moru curry",
    meal: ["lunch", "dinner"],
    category: "curry",
    servings: [
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 150.0,
        calories: 74,
        protein: 2.3,
        fat: 5.3,
        carbs: 4.6,
        fiber: 0.9,
      },
      {
        type: "cup",
        quantity: 1,
        weight_grams: 250.0,
        calories: 123,
        protein: 3.8,
        fat: 8.8,
        carbs: 7.7,
        fiber: 1.5,
      },
      {
        type: "bowl",
        quantity: 1,
        weight_grams: 350.0,
        calories: 172,
        protein: 5.4,
        fat: 12.3,
        carbs: 10.7,
        fiber: 2.0,
      },
    ],
  },
  {
    name: "parippu curry",
    meal: ["lunch", "dinner"],
    category: "curry",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 250.0,
        calories: 228,
        protein: 10.3,
        fat: 8.9,
        carbs: 27.3,
        fiber: 5.5,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 150.0,
        calories: 137,
        protein: 6.2,
        fat: 5.3,
        carbs: 16.4,
        fiber: 3.3,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 350.0,
        calories: 320,
        protein: 14.4,
        fat: 12.4,
        carbs: 38.3,
        fiber: 7.7,
      },
    ],
  },
  {
    name: "pacha moru",
    meal: ["lunch", "dinner"],
    category: "curry",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 250.0,
        calories: 52,
        protein: 2.6,
        fat: 2.8,
        carbs: 4.5,
        fiber: 0.7,
      },
      {
        type: "glass",
        quantity: 1,
        weight_grams: 250.0,
        calories: 52,
        protein: 2.6,
        fat: 2.8,
        carbs: 4.5,
        fiber: 0.7,
      },
    ],
  },
];

const vegSides = [
  {
    name: "cabbage thoran",
    meal: ["lunch", "dinner"],
    category: "veg side",
    subCategory: "thoran",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 166.0,
        calories: 152,
        protein: 4.0,
        fat: 9.1,
        carbs: 14.0,
        fiber: 5.3,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 100.0,
        calories: 92,
        protein: 2.4,
        fat: 5.5,
        carbs: 8.4,
        fiber: 3.2,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 233.0,
        calories: 214,
        protein: 5.5,
        fat: 12.8,
        carbs: 19.6,
        fiber: 7.4,
      },
    ],
  },
  {
    name: "beetroot thoran",
    meal: ["lunch", "dinner"],
    category: "veg side",
    subCategory: "thoran",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 166.0,
        calories: 150,
        protein: 3.2,
        fat: 8.6,
        carbs: 15.5,
        fiber: 5.9,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 100.0,
        calories: 90,
        protein: 1.9,
        fat: 5.2,
        carbs: 9.3,
        fiber: 3.6,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 233.0,
        calories: 211,
        protein: 4.4,
        fat: 12.0,
        carbs: 21.7,
        fiber: 8.3,
      },
    ],
  },
  {
    name: "vazhakkai thoran",
    meal: ["lunch", "dinner"],
    category: "veg side",
    subCategory: "thoran",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 166.0,
        calories: 235,
        protein: 2.5,
        fat: 13.3,
        carbs: 29.4,
        fiber: 4.8,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 100.0,
        calories: 142,
        protein: 1.5,
        fat: 8.0,
        carbs: 17.7,
        fiber: 2.9,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 233.0,
        calories: 330,
        protein: 3.5,
        fat: 18.6,
        carbs: 41.3,
        fiber: 6.7,
      },
    ],
  },

  {
    name: "kovakka mezhukkupuratti",
    meal: ["lunch", "dinner"],
    category: "veg side",
    subCategory: "mezhukkupuratti",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 166.0,
        calories: 116,
        protein: 2.9,
        fat: 8.2,
        carbs: 8.2,
        fiber: 5.6,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 100.0,
        calories: 70,
        protein: 1.8,
        fat: 4.9,
        carbs: 4.9,
        fiber: 3.4,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 233.0,
        calories: 164,
        protein: 4.1,
        fat: 11.5,
        carbs: 11.4,
        fiber: 7.9,
      },
    ],
  },
  {
    name: "payar mezhukkupuratti",
    meal: ["lunch", "dinner"],
    category: "veg side",
    subCategory: "mezhukkupuratti",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 166.0,
        calories: 147,
        protein: 5.6,
        fat: 6.7,
        carbs: 17.0,
        fiber: 5.3,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 100.0,
        calories: 89,
        protein: 3.4,
        fat: 4.1,
        carbs: 10.2,
        fiber: 3.2,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 233.0,
        calories: 207,
        protein: 7.8,
        fat: 9.5,
        carbs: 23.8,
        fiber: 7.4,
      },
    ],
  },
  {
    name: "vazhakka mezhukkupuratti",
    meal: ["lunch", "dinner"],
    category: "veg side",
    subCategory: "mezhukkupuratti",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 166.0,
        calories: 215,
        protein: 2.2,
        fat: 10.8,
        carbs: 30.3,
        fiber: 4.7,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 100.0,
        calories: 129,
        protein: 1.4,
        fat: 6.5,
        carbs: 18.3,
        fiber: 2.9,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 233.0,
        calories: 301,
        protein: 3.2,
        fat: 15.2,
        carbs: 42.5,
        fiber: 6.6,
      },
    ],
  },
  {
    name: "avial",
    meal: ["lunch", "dinner"],
    category: "veg side",
    subCategory: "others",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 250.0,
        calories: 190,
        protein: 3.2,
        fat: 10.9,
        carbs: 20.0,
        fiber: 6.5,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 150.0,
        calories: 114,
        protein: 1.9,
        fat: 6.5,
        carbs: 12.0,
        fiber: 3.9,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 350.0,
        calories: 266,
        protein: 4.4,
        fat: 15.3,
        carbs: 28.0,
        fiber: 9.0,
      },
    ],
  },
  {
    name: "vegetable theeyal",
    meal: ["lunch", "dinner"],
    category: "veg side",
    subCategory: "others",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 250.0,
        calories: 244,
        protein: 4.1,
        fat: 16.3,
        carbs: 21.7,
        fiber: 9.5,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 150.0,
        calories: 146,
        protein: 2.5,
        fat: 9.8,
        carbs: 13.0,
        fiber: 5.7,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 350.0,
        calories: 341,
        protein: 5.8,
        fat: 22.8,
        carbs: 30.4,
        fiber: 13.3,
      },
    ],
  },
];

const nonVegSidesFish = [
  {
    name: "mathi curry",
    meal: ["lunch", "dinner"],
    category: "non-veg side",
    subCategory: "fish",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 250.0,
        calories: 273,
        protein: 24.7,
        fat: 15.5,
        carbs: 9.4,
        fiber: 4.3,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 150.0,
        calories: 164,
        protein: 14.8,
        fat: 9.3,
        carbs: 5.7,
        fiber: 2.6,
      },

      {
        type: "bowl",
        quantity: 1,
        weight_grams: 350.0,
        calories: 383,
        protein: 34.6,
        fat: 21.7,
        carbs: 13.2,
        fiber: 6.1,
      },
    ],
  },
  {
    name: "mathi fry",
    meal: ["lunch", "dinner"],
    category: "non-veg side",
    subCategory: "fish",
    servings: [
      {
        type: "piece",
        quantity: 1,
        weight_grams: 38.0,
        calories: 66,
        protein: 6.9,
        fat: 4.0,
        carbs: 1.0,
        fiber: 0.5,
      },
    ],
  },
];

const nonVegSidesChicken = [
  {
    name: "nadan chicken curry",
    meal: ["lunch", "dinner"],
    category: "non-veg side",
    subCategory: "chicken",
    servings: [
      {
        type: "cup",
        quantity: 1,
        weight_grams: 250.0,
        calories: 332,
        protein: 30.0,
        fat: 19.5,
        carbs: 9.2,
        fiber: 2.7,
      },
      {
        type: "small bowl",
        quantity: 1,
        weight_grams: 150.0,
        calories: 199,
        protein: 18.0,
        fat: 11.7,
        carbs: 5.5,
        fiber: 1.6,
      },
      {
        type: "bowl",
        quantity: 1,
        weight_grams: 350.0,
        calories: 465,
        protein: 42.0,
        fat: 27.3,
        carbs: 12.8,
        fiber: 3.7,
      },
    ],
  },
];

const snacks = [
  {
    name: "pazham pori",
    category: "snack",
    servings: [
      {
        type: "piece",
        quantity: 1,
        weight_grams: 30.0,
        calories: 69,
        protein: 0.7,
        fat: 3.9,
        carbs: 7.9,
        fiber: 0.4,
      },
    ],
  },
  {
    name: "uzhunnu vada",
    category: "snack",
    servings: [
      {
        type: "piece",
        quantity: 1,
        weight_grams: 20.0,
        calories: 41,
        protein: 1.5,
        fat: 2.2,
        carbs: 3.9,
        fiber: 0.7,
      },
    ],
  },
  {
    name: "egg puffs",
    category: "snack",
    servings: [
      {
        type: "piece",
        quantity: 1,
        weight_grams: 50.0,
        calories: 162,
        protein: 3.7,
        fat: 11.1,
        carbs: 11.9,
        fiber: 0.7,
      },
    ],
  },
];

const beverages = [
  // beverages
  {
    name: "tea",
    meal: ["breakfast", "snack"],
    category: "beverages",
    servings: [
      {
        type: "teacup",
        quantity: 1,
        volume_ml: 180.0,
        calories: 73,
        protein: 3.0,
        fat: 3.2,
        carbs: 8.3,
        fiber: 0.0,
      },
      {
        type: "teacup",
        quantity: 1,
        volume_ml: 250.0,
        calories: 101,
        protein: 4.2,
        fat: 4.4,
        carbs: 11.5,
        fiber: 0.0,
      },
    ],
  },
  {
    name: "coffee",
    meal: ["breakfast", "snack"],
    category: "beverages",
    servings: [
      {
        type: "teacup",
        quantity: 1,
        volume_ml: 180.0,
        calories: 133,
        protein: 4.9,
        fat: 5.9,
        carbs: 15.4,
        fiber: 0.0,
      },
      {
        type: "cup",
        quantity: 1,
        volume_ml: 250.0,
        calories: 184,
        protein: 6.8,
        fat: 8.2,
        carbs: 21.4,
        fiber: 0.0,
      },
    ],
  },
];

const accompaniments = [
  {
    name: "pappadam",
    meal: ["breakfast", "lunch", "dinner"],
    category: "accompaniments",
    servings: [
      {
        type: "piece",
        quantity: 1,
        weight_grams: 11.5,
        calories: 46,
        protein: 2.1,
        fat: 1.6,
        carbs: 5.9,
        fiber: 0.1,
      },
    ],
  },
  {
    name: "manga achar",
    meal: ["lunch", "dinner"],
    category: "achar",
    servings: [
      {
        type: "tablespoon",
        quantity: 1,
        weight_grams: 15.0,
        calories: 29,
        protein: 0.2,
        fat: 2.6,
        carbs: 1.4,
        fiber: 0.5,
      },
      {
        type: "teaspoon",
        quantity: 1,
        weight_grams: 5.0,
        calories: 10,
        protein: 0.1,
        fat: 0.9,
        carbs: 0.5,
        fiber: 0.2,
      },
    ],
  },
  {
    name: "mango pickle",
    meal: ["lunch", "dinner"],
    category: "pickle",
    servings: [
      {
        type: "tablespoon",
        quantity: 1,
        weight_grams: 15.0,
        calories: 29,
        protein: 0.2,
        fat: 2.6,
        carbs: 1.4,
        fiber: 0.5,
      },
      {
        type: "teaspoon",
        quantity: 1,
        weight_grams: 5.0,
        calories: 10,
        protein: 0.1,
        fat: 0.9,
        carbs: 0.5,
        fiber: 0.2,
      },
    ],
  },
  {
    name: "lemon pickle",
    meal: ["lunch", "dinner"],
    category: "pickle",
    servings: [
      {
        type: "tablespoon",
        quantity: 1,
        weight_grams: 15.0,
        calories: 19,
        protein: 0.2,
        fat: 1.5,
        carbs: 1.6,
        fiber: 0.5,
      },
      {
        type: "teaspoon",
        quantity: 1,
        weight_grams: 5.0,
        calories: 6,
        protein: 0.1,
        fat: 0.5,
        carbs: 0.5,
        fiber: 0.2,
      },
    ],
  },
];

const hi = {
  name: "",
  category: "",
  servings: [{}],
};

const saveFood = async () => {
  try {
    await client.connect();
    const database = client.db("test"); // Database name
    const collection = database.collection("foods"); // Collection name

    const allFoods = [
      ...mainDishes,
      ...curries,
      ...vegSides,
      ...nonVegSidesFish,
      ...nonVegSidesChicken,
      ...snacks,
      ...beverages,
      ...accompaniments,
    ];

    const result = await collection.insertMany(allFoods);

    // console.log("Food added with _id:", result.insertedId);
  } catch (err) {
    console.error("Error inserting food:", err);
  } finally {
    await client.close();
  }
};

saveFood();
